config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  get 'service/fast_service'
  root 'service#fast_service'
  get 'service/new'
 

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  def  mun_city
    #{}"#{dpto}  /  #{mun}"
  end

  def group_cities
    #@grouped_options={}
    #cities=City.all
    #cities.each do |row|
      #@grouped_options[row.dpto].push(row.mun)
    #end
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/cus_address.rb
class CusAddress < ActiveRecord::Base
  belongs_to :customer
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :user
end

app/models/del_address.rb
class DelAddress < ActiveRecord::Base
  belongs_to :transporter
end

app/models/rem_status.rb
class RemStatus < ActiveRecord::Base
  belongs_to :remittance
end

app/models/remittance.rb
class Remittance < ActiveRecord::Base
  belongs_to :customer
  belongs_to :rem_status
  belongs_to :service
  belongs_to :del_address
end

app/models/service.rb
class Service < ActiveRecord::Base
  Cities.data_path = "lib/tasks/cities"
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :cities
end

app/models/transporter.rb
class Transporter < ActiveRecord::Base
  belongs_to :company
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :name, :lastname, :phone, :email, :password
  #validates_uniqueness_of :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :transporter
  belongs_to :user_status
  belongs_to :user_type

  
end

app/models/user_status.rb
class UserStatus < ActiveRecord::Base
  belongs_to :user
end

app/models/user_type.rb
class UserType < ActiveRecord::Base
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :transporter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_action :configure_permitted_parameters,
                if: :devise_controller?

  protect_from_forgery with: :exception

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit(:email,
                  :phone,
                 :password,
                 :password_confirmation,
                 :name,
                 :lastname)
    end
  end
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
 
  def municipios

  end
  def index

  end

  def fast_service
    @cities=City.all
    @states=State.all
    
  end
  def new
    @service=Service.new
  end


end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
 def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Usuario creado!'
      redirect_to '/'
    else
      flash[:alert] = 'Verificar datos'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :lastname, :phone, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Opttrans</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  
  <%= render 'shared/navbar' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/service/fast_service.html.erb
<header>
  <div id="jumbotron">
    <%=grouped_collection_select(:city, :state_id, @states, :cities, "dpto", :id, "mun", { :selected => [ 'BOGOTÁ D.C.' ]}, {:id => "select-gear" })%>
  </div>
</header>
<section>
</section>

app/views/service/index.html.erb
<h1>Service#index</h1>
<p>Find me in app/views/service/index.html.erb</p>

app/views/service/new.html.erb
<%= form_for @service, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :body, size: "60x12" %>
  <%= f.submit "Create" %>
<% end %>

<%= f.select(
  :user, 
  User.not_god.map{|u| [u.to_s, u.id]}, 
  {}, 
  { id: 'user-select' } 
 ) %>

app/views/shared/_navbar.html.erb
<nav>

      <ul class="ul1">
          <li><a href="html5_semantic_elements.asp">Home</a></li>
          <li><a href="html5_geolocation.asp">Servicios</a></li>
          <li><a href="html5_canvas.asp">Contáctanos</a></li>
      </ul>
      
      <ul class="ul2">
        <li><% if user_signed_in?%>
               <%= link_to current_user.email, edit_user_registration_path%>
            <% end %></li>
        <% if current_user.nil? %>
          <li><a href="<%=new_user_session_path%>">Inicia sesión</a></li>
          <li><a href="<%=new_user_registration_path%>">Regístrate</a></li>
        <% else %>
          <li><a href="<%=destroy_user_session_path%>" data-method="delete">Salir</a></li>
        <% end %>
      </ul>

  </nav>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>